
name: Create crate dist
on:
  push:
    tags:
      - '**'

jobs:
  crate-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create crate dist
        uses: projg2/crate-dist-action@v1
        with:
          directories: minify-html-python
          dist-filename: minify-html-0.17.1-crates.tar.xz
          run-cargo-update: false

